### PR TITLE
Fixes #37

### LINKED ISSUE #37: Chart won't display under native shadow dom (v3.0.0)
I tracked it down to Chart.js trying to get and work with the parent node. Under shadow dom it get's a document fragment with doesn't provide what Cart.js expects. Wrapping the canvas element in a div resolves the issue. I'll propose a pr for this.

### PR DESCRIPTION
**Pull request by pkaske**

### CODE REVIEW

**Comment by robdodson** [comment]
Cool, it looks like this PR also contains the changed from #36 so would you be ok with closing 36 and we can just merge in this one?

**Comment by pkaske** [comment]
Yep!

**Comment by robdodson** [comment]
Also looks like the tests are failing but that seems to be because the web component tester setup is a little busted :P

Also I was wondering if you'd like to be added as a maintainer to this project? I'd like the folks who actually use the elements to have the power to merge in fixes without waiting on me :)

**Comment by pkaske** [comment]
Sure, that's cool with me.

**Comment by robdodson** [comment]
Great! Added you as a contributor. You should now be able to merge PRs and cut tags :)

**Comment by pkaske** [comment]
:)

**Pull request merged**
